- name: Ansible playbook to dockerize and run Yolo e-commerce app using Ansible
  hosts: all
  become: true

  pre_tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: yes
      register: docker_installed

    - name: Install Docker if not installed
      apt:
        name: docker.io
        state: present
      when: docker_installed.failed

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true
      when: docker_installed.failed

    - name: Create Docker network
      docker_network:
        name: app-net
        state: present

  roles:
    - role: setup-mongodb
    - role: frontend-deployment
    - role: backend-deployment

  tasks:
    # Removed Kubernetes deployment tasks

  post_tasks:
    # Removed verification tasks for Kubernetes services